details:
  name: Fundamentals
  repository_name: unit-fundamentals

sequence:
############################################################
#               SPRINT 1
############################################################
  Core JavaScript:
    # Block 1
    - name: Core Tools Setup
      elements:
        - kind: guide
          pursuit_path: computer-setup
          pursuit_subpath: core-tools
        - kind: recording
    - name: Introduction to Algorithms
      pursuit_path: intro-to-algorithms
      kind: lesson
      activity: canvas_text
      activity_description: "<p>To complete this lab, you will need to write an algorithm in plain language. You will not need to write any code to complete this Lab.</p>

      <p>Write an algorithm that achieves the following outcome: looking up a word in an online or physical dictionary. Keep in mind any inputs a person may need and the desired output. Additionally, focus on designing for the default scenario (i.e., 'happy path') before thinking about edge cases. If there are any edge cases you think are important to keep in mind, include them at the end.</p>

      <p>Do not spend more than 30 - 45 minutes on this Lab.</p>"
    # Block 2
    - name: Introduction to Code
      pursuit_path: intro-to-code
      kind: lesson
      activity: canvas_text
      activity_description: "<p>To complete this lab, answer the following question:</p>
      
      <p>How does learning a coding language help you communicate with a computer? Provide as much detail as you can.</p>"
    - name: Problem Solving Methodologies
      pursuit_path: problem-solving-methodologies
      kind: lesson
      activity: canvas_text
      activity_description: "<p>To complete this lab, answer the following question:</p>
      
      <p>What is Polya's Problem Solving Technique and how can it be applied to your daily life? Provide as much detail as you can.</p>"
    # Block 3
    - name: Replit Setup
      elements:
        - kind: guide
          pursuit_path: external-tools
          pursuit_subpath: replit
        - kind: recording
    - name: Introduction to JavaScript
      pursuit_path: intro-to-javascript
      kind: lesson
      activity: replit
    # Block 4
    - name: Control Flow 
      pursuit_path: control-flow
      kind: lesson
      activity: replit
    # Block 5
    - name: Loops 
      pursuit_path: loops
      kind: lesson
      activity: replit
    # Block 6
    - name: Functions 
      pursuit_path: functions
      kind: lesson
      activity: replit
    # Block 7
    - name: Common Errors 
      pursuit_path: common-errors
      kind: lesson
      activity: replit
    - name: Understanding Code Challenges 
      pursuit_path: understanding-code-challenges
      kind: lesson
      activity: replit     
    # Block 8
    - name: Scope 
      pursuit_path: scope
      kind: lesson
      activity: replit
    # Block 9
    - name: Arrays 
      pursuit_path: arrays
      kind: lesson
      activity: replit
    # Block 10
    - name: Common Methods and Tools 
      pursuit_path: common-methods-and-tools
      kind: lesson
      activity: replit
    # Project
    - name: Skill Sharpening
      pursuit_path: skill-sharpening
      kind: project
      activity: replit
      points_possible: 100 
############################################################
#               SPRINT 2
############################################################
  Problem Solving with Code:
    # Block 1
    - name: Objects
      pursuit_path: objects
      kind: lesson
      activity: replit
    # Block 2
    - name: Data Representation with Code
      pursuit_path: data-representation-with-code
      kind: lesson
      activity: replit
    # Block 3
    - name: Looping through Arrays with Objects
      pursuit_path: array-object-loops
      kind: lesson
      activity: replit
    # Block 4
    - name: Modern JavaScript Features
      pursuit_path: modern-javascript-features
      kind: lesson
      activity: replit
    # Block 5
    - name: Evaluating Expressions
      pursuit_path: evaluating-expressions
      kind: lesson
      activity: replit
    # Block 6
    - name: Nested Loops
      pursuit_path: nested-loops
      kind: lesson
      activity: replit 
    # Block 7
    - name: Reference Types
      pursuit_path: reference-types
      kind: lesson
      activity: replit
    # Block 8
    - name: Accumulator Pattern
      pursuit_path: accumulator-pattern
      kind: lesson
      activity: replit
    # Project
    - name: Trinkets and Treasures
      pursuit_path: Trinkets and Treasures
      kind: project
      activity: replit
      points_possible: 100
############################################################
#               SPRINT 3
############################################################
  Advanced Software Development Skills:
    # Block 1
    - name: Common Algorithms
      pursuit_path: common-algorithms
      kind: lesson
      activity: canvas_text
      activity_description: "<p>To complete this lab, answer the following question:</p>
      
      <p>Imagine you are tasked with explaining the accumulator pattern to someone unfamiliar with any programming languages. How would you convey the concept and its significance using everyday language?</p>"
    - name: Tinkerer Mindset
      pursuit_path: tinkerer-mindset
      kind: lesson
      activity: replit

    # Block 2
    - name: Technical Communication
      pursuit_path: technical-communication
      kind: lesson
      activity: canvas_url
      activity_description: "<p>Revisit a recent project or lab you completed in this course. Choose two functions in that project or lab and add comments to your solution that explain how the code works. Make sure to use technical language throughout.</p>

      <p>Once you're done, resubmit a link to that project or lab as part of this assignment.</p>"
    - name: Markdown
      pursuit_path: markdown
      kind: lesson
      activity: repository

    # Block 3
    - name: Programming Principles
      pursuit_path: programming-principles
      kind: lesson
      # no activity
    - name: Program Design
      pursuit_path: program-design
      kind: lesson
      activity: canvas_url
      activity_description: "<p>Revisit a recent project or lab you completed in this course. Choose a function in that project or lab that could be improved based on what you learned in the Programming Principles or Program Design lessons. Update the code to make it more readable or organized. Then, add a comment above the function describing what you changed.</p>

      <p>Once you're done, resubmit a link to that project or lab as part of this assignment.</p>"

    # Block 4
    - name: Measuring Complexity
      pursuit_path: measuring-complexity
      kind: lesson
      activity: canvas_url
      activity_description: "<p>Revisit the most recent project you completed in this course. Add a comment underneath each function for that project that describes the time complexity of the function.</p>

      <p>Once you're done, resubmit a link to that project as part of this assignment.</p>"

    # Block 5
    - name: Recursion
      pursuit_path: recursion
      kind: lesson
      activity: canvas_url
      activity_description: "<p>Revisit a recent project or lab you completed in this course. Choose two functions in that project or lab that use loops and convert the functions to recursive functions.</p>

      <p>Once you're done, resubmit a link to that project or lab as part of this assignment.</p>"

    # Block 6
    - name: Binary Search
      pursuit_path: binary-search
      kind: lesson
      # no activity

    # Project
    - name: Independent Study
      pursuit_path: independent-study
      kind: project
      activity: repository
      points_possible: 60 
    - name: Independent Study Presentation
      kind: project
      activity: presentation
      points_possible: 40 

    # Block 7
    - name: Codetrack
      elements:
        - kind: guide
          pursuit_path: external-tools
          pursuit_subpath: codetrack
        - kind: recording

############################################################
#               SPRINT 4
############################################################
  Program Like a Developer:
    # Block 1
    - name: Local Environment Setup
      elements:
        - kind: guide
          pursuit_path: computer-setup
          pursuit_subpath: local-environment
        - kind: recording
    - name: Introduction to the Command Line
      pursuit_path: intro-to-command-line
      kind: lesson
      activity: repository
    
    # Block 2
    - name: Git
      pursuit_path: git
      kind: lesson
      activity: repository
    
    # Block 3
    - name: GitHub Setup
      elements:
        - kind: guide
          pursuit_path: external-tools
          pursuit_subpath: github
        - kind: recording
    - name: GitHub
      pursuit_path: github
      kind: lesson
      activity: repository
    - name: Submit GitHub Username
      kind: task
      activity: canvas_url
      activity_description: "<p>Once you sign up for GitHub, submit the URL to your GitHub profile. It should have the following format, where 

      <code>&lt;YOUR-USERNAME&gt;</code> is replaced with your username.</p>

      <pre>https://github.com/&lt;YOUR-USERNAME&gt;</pre>

      <p>You should be able to copy and paste from the location bar in your browser.</p>"
      points_possible: 0

    # Block 4
    - name: JavaScript on Your Machine
      pursuit_path: javascript-on-your-machine
      kind: lesson
      activity: repository
    
    # Block 56
    - name: Higher Order Functions
      pursuit_path: higher-order-functions
      kind: lesson
      activity: repository
    
    # Block 6 & 7
    - name: Higher Order Native Array Methods
      pursuit_path: higher-order-native-array-methods
      kind: lesson
      activity: repository
    
    # Project
    - name: Dinosaur Museum
      pursuit_path: dinosaur-museum
      kind: project
      activity: repository
      points_possible: 80 
    - name: Dinosaur Museum Presentation
      kind: project
      activity: presentation
      points_possible: 20 
    - name: End of Module Reflection
      elements:
        - kind: deck
        - kind: recording